/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f4",
        "surface-container": "#eceeee",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e3",
        "surface-dim": "#d8dada",
        "surface-bright": "#f8fafa",
        "surface-variant": "#e1e3e3",
        "surface": "#f8fafa",
        "surface-tint": "#006b5f",
        "background": "#f8fafa",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3c4946",
        "inverse-surface": "#2e3131",
        "inverse-on-surface": "#eff1f1",
        "primary": "#006b5f",
        "on-primary": "#ffffff",
        "primary-container": "#00a896",
        "on-primary-container": "#00352e",
        "primary-fixed": "#79f7e3",
        "primary-fixed-dim": "#59dbc7",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005047",
        "inverse-primary": "#59dbc7",
        "secondary": "#895100",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd9d1a",
        "on-secondary-container": "#663b00",
        "secondary-fixed": "#ffdcbc",
        "secondary-fixed-dim": "#ffb86b",
        "on-secondary-fixed": "#2c1700",
        "on-secondary-fixed-variant": "#683d00",
        "tertiary": "#006a62",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00a89b",
        "on-tertiary-container": "#003530",
        "tertiary-fixed": "#70f8e8",
        "tertiary-fixed-dim": "#4fdbcc",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#005049",
        "outline": "#6c7a76",
        "outline-variant": "#bbcac5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0px 20px 40px rgba(25, 28, 29, 0.06)",
        "ambient-sm": "0px 10px 20px rgba(25, 28, 29, 0.05)",
        primary: "0px 20px 40px rgba(0, 107, 95, 0.15)",
        "primary-sm": "0px 10px 20px rgba(0, 107, 95, 0.20)",
      },
    },
  },
  plugins: [],
}
